// Curated Paris places knowledge base for the touristAgent chatbot grounding.
// Generated from data/build_places.py; human-facing copy: data/paris-places.xlsx.
// Verified 2026-07-23 (2026 prices + open/closed status). Unknowns are honest, not guessed.

export type PlaceCategory =
  | "Monument"
  | "Museum"
  | "Cathedral"
  | "Basilica"
  | "Park"
  | "Palace"
  | "Shopping";

export interface Place {
  id: string;
  nameEn: string;
  nameFr: string;
  category: PlaceCategory;
  arrondissement: string;
  coord: { lat: number; lng: number };
  visitDuration: string;
  budget: string; // adult entry cost in EUR, or "Free"
  free: boolean; // entry to the site is free
  openingHours: string;
  nearestTransit: string;
  stationStepFree: string;
  wheelchair: string;
  accessibleToilet: string;
  status: "open" | "closed";
  officialUrl: string;
  source: string;
  lastVerified: string;
  notes: string;
}

export const PLACES: Place[] = [
  {
    id: "eiffel-tower",
    nameEn: "Eiffel Tower",
    nameFr: "Tour Eiffel",
    category: "Monument",
    arrondissement: "7th (75007)",
    coord: { lat: 48.8584, lng: 2.2945 },
    visitDuration: "2-3 h",
    budget: "€36.70 summit (lift); €23.50 2nd floor (lift); €14.80 stairs to 2nd",
    free: false,
    openingHours: "≈09:30-23:45 daily (extended in summer)",
    nearestTransit: "RER C Champ de Mars-Tour Eiffel; M6 Bir-Hakeim",
    stationStepFree: "Partial (RER C Champ de Mars step-free; M6 Bir-Hakeim not)",
    wheelchair: "Partial (1st & 2nd floors by lift; summit not accessible)",
    accessibleToilet: "Yes",
    status: "open",
    officialUrl: "https://www.toureiffel.paris/en",
    source: "Official site + web search 2026-07-23",
    lastVerified: "2026-07-23",
    notes: "Summit closed to wheelchair users. Book online in advance.",
  },
  {
    id: "louvre",
    nameEn: "Louvre Museum",
    nameFr: "Musée du Louvre",
    category: "Museum",
    arrondissement: "1st (75001)",
    coord: { lat: 48.8606, lng: 2.3376 },
    visitDuration: "3-4 h (half day)",
    budget: "€22 (EEA residents); €32 (non-EEA)",
    free: false,
    openingHours: "09:00-18:00; late to 21:45 Wed & Fri; closed Tue",
    nearestTransit: "M1/M7 Palais Royal-Musée du Louvre",
    stationStepFree: "Partial (line 14 Pyramides/Châtelet nearby are step-free)",
    wheelchair: "Yes (fully accessible; free for wheelchair users + 1 companion)",
    accessibleToilet: "Yes",
    status: "open",
    officialUrl: "https://www.louvre.fr/en",
    source: "Official site + web search 2026-07-23",
    lastVerified: "2026-07-23",
    notes: "New 2026 dual pricing (EEA vs non-EEA). Free under 18, EU 18-25, 1st Sat evening.",
  },
  {
    id: "notre-dame",
    nameEn: "Notre-Dame Cathedral",
    nameFr: "Cathédrale Notre-Dame de Paris",
    category: "Cathedral",
    arrondissement: "4th (75004)",
    coord: { lat: 48.853, lng: 2.3499 },
    visitDuration: "1 h (cathedral)",
    budget: "Cathedral free; Bell Towers €16",
    free: true,
    openingHours: "≈08:00-19:00 (free reservation online)",
    nearestTransit: "M4 Cité; RER B/C Saint-Michel-Notre-Dame",
    stationStepFree: "Partial (Cité limited)",
    wheelchair: "Yes (cathedral, step-free entrance); No (towers, ~424 steps)",
    accessibleToilet: "Unknown (public toilets nearby)",
    status: "open",
    officialUrl: "https://www.notredamedeparis.fr/en/",
    source: "Official site + web search 2026-07-23",
    lastVerified: "2026-07-23",
    notes: "Reopened Dec 2024; towers reopened Sep 2025. Free timed reservation recommended.",
  },
  {
    id: "arc-de-triomphe",
    nameEn: "Arc de Triomphe",
    nameFr: "Arc de Triomphe",
    category: "Monument",
    arrondissement: "8th (75008)",
    coord: { lat: 48.8738, lng: 2.295 },
    visitDuration: "1 h",
    budget: "€16 (rooftop); free to view from below",
    free: false,
    openingHours: "10:00-22:30 (seasonal)",
    nearestTransit: "M1/M2/M6, RER A Charles de Gaulle-Étoile",
    stationStepFree: "Partial",
    wheelchair: "Partial (rooftop ~284 steps; lift for reduced-mobility visitors on request)",
    accessibleToilet: "Unknown",
    status: "open",
    officialUrl: "https://www.paris-arc-de-triomphe.fr/en",
    source: "Official site (CMN) + web search 2026-07-23",
    lastVerified: "2026-07-23",
    notes: "Reach the arch via the underground passage (no street crossing). Free under 18, EU 18-25.",
  },
  {
    id: "musee-orsay",
    nameEn: "Musée d'Orsay",
    nameFr: "Musée d'Orsay",
    category: "Museum",
    arrondissement: "7th (75007)",
    coord: { lat: 48.86, lng: 2.3266 },
    visitDuration: "2-3 h",
    budget: "€16 online (€14 on-site; €12 Thu evening)",
    free: false,
    openingHours: "09:30-18:00 Tue-Sun; to 21:45 Thu; closed Mon",
    nearestTransit: "RER C Musée d'Orsay; M12 Solférino",
    stationStepFree: "Partial",
    wheelchair: "Yes (accessible)",
    accessibleToilet: "Yes",
    status: "open",
    officialUrl: "https://www.musee-orsay.fr/en",
    source: "Official site + web search 2026-07-23",
    lastVerified: "2026-07-23",
    notes: "Free 1st Sunday of month; free under 18, EU 18-25. Reservation mandatory.",
  },
  {
    id: "sacre-coeur",
    nameEn: "Sacré-Cœur Basilica",
    nameFr: "Basilique du Sacré-Cœur",
    category: "Basilica",
    arrondissement: "18th (75018)",
    coord: { lat: 48.8867, lng: 2.3431 },
    visitDuration: "1-1.5 h",
    budget: "Basilica free; dome ≈€8 (confirm)",
    free: true,
    openingHours: "06:30-22:30 (basilica)",
    nearestTransit: "M2 Anvers + funicular; M12 Abbesses",
    stationStepFree: "No (hilltop; deep stations with stairs; funicular to summit)",
    wheelchair: "Partial (step-free side access to basilica; hill is difficult; dome not accessible)",
    accessibleToilet: "Unknown",
    status: "open",
    officialUrl: "https://www.sacre-coeur-montmartre.com/english/",
    source: "Official site + knowledge; dome price not re-verified",
    lastVerified: "2026-07-23",
    notes: "Confirm dome price/access on official site. Funicular covered by a metro ticket.",
  },
  {
    id: "sainte-chapelle",
    nameEn: "Sainte-Chapelle",
    nameFr: "Sainte-Chapelle",
    category: "Monument",
    arrondissement: "1st (75001)",
    coord: { lat: 48.8554, lng: 2.345 },
    visitDuration: "45 min-1 h",
    budget: "€12 (combo with Conciergerie €20)",
    free: false,
    openingHours: "09:00-19:00 (seasonal)",
    nearestTransit: "M4 Cité; RER B/C Saint-Michel",
    stationStepFree: "Partial",
    wheelchair: "Partial (lower chapel step-free; upper chapel via spiral stairs, not accessible)",
    accessibleToilet: "Unknown",
    status: "open",
    officialUrl: "https://www.sainte-chapelle.fr/en",
    source: "Official site (CMN) + web search 2026-07-23",
    lastVerified: "2026-07-23",
    notes: "Airport-style security (active courthouse). Upper-chapel stained glass is the highlight.",
  },
  {
    id: "pantheon",
    nameEn: "Panthéon",
    nameFr: "Panthéon",
    category: "Monument",
    arrondissement: "5th (75005)",
    coord: { lat: 48.8462, lng: 2.3464 },
    visitDuration: "1 h",
    budget: "≈€13 (2025 estimate; confirm 2026)",
    free: false,
    openingHours: "10:00-18:30 (seasonal)",
    nearestTransit: "RER B Luxembourg; M10 Cardinal Lemoine",
    stationStepFree: "Partial",
    wheelchair: "Partial (nave accessible; dome via stairs, not accessible)",
    accessibleToilet: "Unknown",
    status: "open",
    officialUrl: "https://www.paris-pantheon.fr/en",
    source: "Official site (CMN); 2026 price NOT verified",
    lastVerified: "2026-07-23 (price is a 2025 estimate)",
    notes: "Price is a 2025 estimate, confirm 2026 on the official site. Crypt of French notables; Foucault pendulum.",
  },
  {
    id: "jardin-luxembourg",
    nameEn: "Luxembourg Garden",
    nameFr: "Jardin du Luxembourg",
    category: "Park",
    arrondissement: "6th (75006)",
    coord: { lat: 48.8462, lng: 2.3372 },
    visitDuration: "1 h",
    budget: "Free",
    free: true,
    openingHours: "≈07:30-21:00 (seasonal, dawn-dusk)",
    nearestTransit: "RER B Luxembourg; M4 Saint-Sulpice",
    stationStepFree: "Partial",
    wheelchair: "Yes (main paths; some gravel surfaces)",
    accessibleToilet: "Yes",
    status: "open",
    officialUrl: "https://www.senat.fr/visite/jardin/index.html",
    source: "Official site + knowledge",
    lastVerified: "2026-07-23",
    notes: "Free public garden. Gravel paths can be hard for small wheels.",
  },
  {
    id: "jardin-tuileries",
    nameEn: "Tuileries Garden",
    nameFr: "Jardin des Tuileries",
    category: "Park",
    arrondissement: "1st (75001)",
    coord: { lat: 48.8635, lng: 2.3275 },
    visitDuration: "1 h",
    budget: "Free",
    free: true,
    openingHours: "≈07:00-21:00 (seasonal)",
    nearestTransit: "M1 Tuileries / Concorde",
    stationStepFree: "Partial",
    wheelchair: "Yes (mostly flat; gravel surfaces)",
    accessibleToilet: "Yes",
    status: "open",
    officialUrl: "https://www.louvre.fr/en/explore/the-palace/the-tuileries-garden",
    source: "Official site + knowledge",
    lastVerified: "2026-07-23",
    notes: "Links the Louvre to Place de la Concorde. Gravel paths.",
  },
  {
    id: "chateau-versailles",
    nameEn: "Palace of Versailles",
    nameFr: "Château de Versailles",
    category: "Palace",
    arrondissement: "Versailles (78000, Yvelines)",
    coord: { lat: 48.8049, lng: 2.1204 },
    visitDuration: "half-full day",
    budget: "Passport €25 (low)-€35 (high); Palace only €21",
    free: false,
    openingHours: "09:00-18:30; closed Mon",
    nearestTransit: "RER C Versailles Château Rive Gauche",
    stationStepFree: "Partial",
    wheelchair: "Yes (accessible; free for disabled visitors + companion; adapted routes)",
    accessibleToilet: "Yes",
    status: "open",
    officialUrl: "https://en.chateauversailles.fr",
    source: "Official site + web search 2026-07-23",
    lastVerified: "2026-07-23",
    notes: "Outside Paris (~40 min by RER C). EEA reduced rates. Gardens paid on Musical Fountains days.",
  },
  {
    id: "galeries-lafayette",
    nameEn: "Galeries Lafayette Haussmann",
    nameFr: "Galeries Lafayette Haussmann",
    category: "Shopping",
    arrondissement: "9th (75009)",
    coord: { lat: 48.8738, lng: 2.332 },
    visitDuration: "1-2 h",
    budget: "Free entry (shopping)",
    free: true,
    openingHours: "10:00-20:00; Sun 11:00-20:00",
    nearestTransit: "M7/M9 Chaussée d'Antin-La Fayette; RER A Auber",
    stationStepFree: "Partial",
    wheelchair: "Yes (department store with lifts)",
    accessibleToilet: "Yes",
    status: "open",
    officialUrl: "https://haussmann.galerieslafayette.com/en/",
    source: "Official site + knowledge",
    lastVerified: "2026-07-23",
    notes: "Belle Époque glass dome; free rooftop terrace with city views.",
  },
  {
    id: "centre-pompidou",
    nameEn: "Centre Pompidou",
    nameFr: "Centre Pompidou",
    category: "Museum",
    arrondissement: "4th (75004)",
    coord: { lat: 48.8607, lng: 2.3522 },
    visitDuration: "N/A",
    budget: "N/A (closed)",
    free: false,
    openingHours: "Closed",
    nearestTransit: "M11 Rambuteau; M1/4/7/11/14 Châtelet",
    stationStepFree: "Partial",
    wheelchair: "N/A (closed)",
    accessibleToilet: "N/A",
    status: "closed",
    officialUrl: "https://www.centrepompidou.fr/en/",
    source: "Official site + web search 2026-07-23",
    lastVerified: "2026-07-23",
    notes: "Closed for a 5-year renovation until 2030. Collection shown at partner venues (Constellation programme). Do NOT recommend visiting.",
  },
];
